/* Generated by convbdf_dct on Thu Dec  2 20:23:23 2010. */

#include "font.h"

extern const font_t font_helvR08;
extern const font_t font_helvR10;
extern const font_t font_helvR12;
extern const font_t font_helvR14;
extern const font_t font_helvR18;
extern const font_t font_helvR24;

const font_t *fonts[] =
{
  &font_helvR08,
  &font_helvR10,
  &font_helvR12,
  &font_helvR14,
  &font_helvR18,
  &font_helvR24,
  0 /* MUST BE LAST! */
};

const unsigned long num_fonts = 6;

