#!/bin/sh
#
# Init S2lm 4G TD-LTE
#



start()
{
   ifconfig eth0 10.0.22.189 netmask 255.255.255.0 up
   sleep1
   route add default gw 10.0.22.1
   /usr/local/bin/init.sh --imx224
   /usr/local/bin/test_image -i 0 &
   sleep 1
   /usr/local/bin/test_encode -i 720p -X --binsize 720p --bsize 720p --bmaxsiz 720p -J --btype off -K --btype off --enc-mode 0
   sleep 1
   /usr/local/bin/rtsp_server &
   sleep 1
   /usr/local/bin/test_encode -A --bitrate 3000000  -m 720p -e & 
    echo "Enable 4G-LTE OK!"
}
stop()
{
     echo "stop 4G-LTE  !"
}

restart()
{
	stop
	start
}

case "$1" in
	start)
	start;;
  stop)
	stop
	;;
	restart|reload)
	restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	esac
	exit $?

