#!/bin/sh
#
# Init RTSP video
#
sensor_name=--imx224

start()
{
    /usr/local/bin/init.sh $sensor_name
    sleep 1
    /usr/local/bin/stream_wifi &
    echo "Enable rtsp OK !"
}
stop()
{
     echo "USB wifi test stop !"
}

restart()
{
	stop
	start
}

case "$1" in
	start)
	start;;
  stop)
	stop
	;;
	restart|reload)
	restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	esac
	exit $?

