#!/bin/sh
#
# Init S2lm usb host mode
#
usbphy0_dir=/proc/ambarella/usbphy0

start()
{
    echo host > $usbphy0_dir
    sleep 1
    mount -t nfs -o nolock 10.0.22.93:/home/dfyuan/projects/ambarella/ambarella_nfs  /mnt
    echo "change usb to host mode and mount nfs server !"
}
stop()
{
     echo "USB wifi test stop !"
}

restart()
{
	stop
	start
}

case "$1" in
	start)
	start;;
  stop)
	stop
	;;
	restart|reload)
	restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	esac
	exit $?

