<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="html"/>
<xsl:decimal-format decimal-separator="." grouping-separator="," />


<!-- ================================================================== -->
<!-- Interprets a xml file generated by ExtXmlOutputter of EmbUnit      -->
<!-- ================================================================== -->
<xsl:template match="/">

    <script type="text/javascript" language="JavaScript"><![CDATA[
    function displayMessage(name) {
        var win = window.open('','Message','scrollbars=1,resizable=1');
        var doc = win.document.open();
        doc.write("<html><head><title>Message</title></head>");
        doc.write("<body><pre>");
        doc.write(name);
        doc.write("</pre></body></html>");
        doc.close();
        win.focus();
    }
    ]]>
    </script>

	<h1 align="center">Test Results</h1>

    <xsl:call-template name="Test.additionalInfo" />

    <table border="0" cellspacing="0" width="100%">
    <xsl:call-template name="table.header" />
    
    <xsl:for-each select="//TestRun">
     <xsl:variable name="suite" select="./*"/>

     <xsl:for-each select="$suite" >
       <xsl:variable name="suitename" select="name()"/>
 
        <xsl:choose>
         <xsl:when test="$suitename='Statistics'"> </xsl:when>
           <xsl:otherwise>
    
            <xsl:call-template name="print.suitename" >
              <xsl:with-param name="currentSuite" select="$suitename" /> 
            </xsl:call-template>
 
         </xsl:otherwise>
        </xsl:choose>

        <xsl:for-each select="Test" >
           <xsl:call-template name="Test.success">
             <xsl:with-param name="currentSuite" select="$suitename" />
           </xsl:call-template>
        </xsl:for-each>

        <xsl:for-each select="FailedTest" >
           <xsl:call-template name="Test.failure">
             <xsl:with-param name="currentSuite" select="$suitename" />
           </xsl:call-template>
        </xsl:for-each>

    </xsl:for-each>
        <xsl:for-each select="Statistics" >
           <xsl:call-template name="Test.statistics"/>
        </xsl:for-each>

    </xsl:for-each>
    </table>
</xsl:template>

<xsl:template name="Test.success">
    <xsl:param name="currentSuite" />

    <tr>
    <xsl:attribute name="class">
          unittests-data
      </xsl:attribute>

       <xsl:attribute name="bgcolor">#EEEEEE</xsl:attribute>
       
       <td/>

       <td colspan="2">
		 <!-- Display the testname only-->
         <!-- <xsl:value-of select="Name"/>-->
         
         <!-- Create a link with an anchor to show the corresponding test-->
         <a><xsl:attribute name="href">../doc/html/<xsl:value-of select="$currentSuite"/>.html#<xsl:value-of select="Name" />
            </xsl:attribute>
              <font color="#0000FF"><xsl:value-of select="Name"/></font>
         </a>
          
        </td>
        
		<td><xsl:value-of select="Comment"/></td>        
 
        <td>
          <xsl:attribute name="bgcolor">#00FF00</xsl:attribute>
          <font color="#FFFFFF">Success</font>
        </td>

        <td>
          <xsl:value-of select="format-number(Test_Time,'0,000')"/>
        </td>

    </tr>
</xsl:template>

<xsl:template name="Test.failure">
    <xsl:param name="currentSuite" />
    
    <tr>

     <xsl:attribute name="class">
          unittests-failure
      </xsl:attribute>
 
       <!-- <xsl:if test="position() div 2 mod 2 = 0">-->
          <xsl:attribute name="bgcolor">#EEEEEE</xsl:attribute>
       <!-- </xsl:if>-->

       <td/>

        <td colspan="2">
         <!-- Create a link with an anchor to show the corresponding test-->
         <a><xsl:attribute name="href">../doc/html/<xsl:value-of select="$currentSuite"/>.html#<xsl:value-of select="Name" />
            </xsl:attribute>
              <font color="#FF0000"><xsl:value-of select="Name"/></font>
              
         </a>

         <!-- <font color="#FF0000"><xsl:value-of select="Name"/></font>-->
        </td>    
        
		<td><xsl:value-of select="Comment"/></td>

        <td>
            <xsl:attribute name="bgcolor">#FF0000</xsl:attribute>
           <a>
              <xsl:attribute name="href">javascript:displayMessage('Test: <xsl:value-of select="Name" /> File: <xsl:value-of select="Location/File"/> Line: <xsl:value-of select="Location/Line"/>  Message: <xsl:value-of select="Message"/>');
              </xsl:attribute>
               <font color="#FFFFFF">Failed &#187;</font>
           </a>
        </td>
        
        <td>
        
          <!-- <xsl:value-of select="format-number(@time,'0.000')"/>-->
          <xsl:value-of select="format-number(Test_Time,'0,000')"/>
        </td>               
    </tr>
        
    
</xsl:template>

<xsl:template name="Test.statistics">
      <tr><td>Tests: <xsl:value-of select="Tests"/> Failures: <xsl:value-of select="Failures"/></td></tr>
</xsl:template>

<xsl:template name="Test.additionalInfo">
<table width="100%" border="0">
    <colgroup>
        <col width="15%"></col>
        <col width="85%"></col>
    </colgroup>

  <tr>
    <td><b>Configspec Label used: </b></td>
    <td> <xsl:value-of select="//Label"/></td>
  </tr>
  <tr>
    <td><b>Test ran at: </b></td>
    <td> <xsl:value-of select="//Time"/></td>
  </tr>
  <tr>
    <td><b>Buildmode: </b></td>
    <td> <xsl:value-of select="//BuildMode"/></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>
<br/>
</xsl:template>


<xsl:template name="table.header" >

    <colgroup>
        <col width="10%"></col>
        <col width="20%"></col>
        <col width="25%"></col>
        <col width="25%"></col>
        <col width="04%"></col>
        <col width="10%"></col>
    </colgroup>
    <tr valign="top" class="unittests-sectionheader" align="left" bgcolor="#0000FF">
        <th colspan="3"><font color="#FFFFFF">Name</font></th>
        <th><font color="#FFFFFF">Comment</font></th>
        <th><font color="#FFFFFF">Status</font></th>
        <th nowrap="nowrap"><font color="#FFFFFF">Time(s)</font></th>
    </tr>
</xsl:template>


<xsl:template name="print.suitename" >
    <xsl:param name="currentSuite" />
    <tr>
        <xsl:attribute name="class">
            <xsl:choose>
                <xsl:when test="testcase/error">unittests-error-title</xsl:when>
                <xsl:when test="testcase/failure">unittests-failure-title</xsl:when>
                <xsl:otherwise>unittests-title</xsl:otherwise>
            </xsl:choose>
        </xsl:attribute>
        
        <xsl:attribute name="bgcolor">#FFFFBB</xsl:attribute>

       <td colspan="6"><font size="3"><b><xsl:value-of select="$currentSuite"/></b></font></td> 
    </tr>
</xsl:template>

</xsl:stylesheet>
